;Draw the tree illustrating the process generated by the count-change procedure of section 1.12 in making change for ;
;11 cents. What are orders of growth of the space and number of steps used by this process as the amount to be changed
;increases?

(count-change 11)
4
;the order of Growth of the space is O(n)
; the number of steps used by this process is 55.

; i'm no t sure if the number of steps answer is correct. Maybe i dont understand this correctly.