;1 - Each of the following two procedures defines a method for adding two positive integers in terms of the procedures inc, 
;which increments its argument by 1, and dec, which decrements its arguments by 1.

;;clojure implementation
1 - (defn add
[a b]
  (if (= a 0)
    b
    (inc (add (dec a) b))))


;2 - 
(defn add 
[a b]
  (if (= a 0)
  b
  (add (dec a) (inc b))))

;Using the substitution model, illustrate the process generated by each procedure in evaluating (add 4 5). Are these process ;iterative or recursive?

;Solutions:

;1 - 
    (add 4 5)
    (inc (add (dec 4) 5))
    (inc (add 3 5))
    (inc (inc (add (dec 3) 5)))
    (inc (inc (add 2 5)))
    (inc (inc (inc (add (dec 2) 5))))
    (inc (inc (inc (add 1 5))))
    (inc (inc (inc (inc (add (dec 1) 5)))))
    (inc (inc (inc (inc (add 0 5)))))
    (inc (inc (inc (inc 5))))
    (inc (inc (inc 6)))
    (inc (inc 7))
    (inc 8)
     9
  
;2 - 
(add 4 5)
    (add (dec 4) (inc 5))
    (add (add 3 6))
    (add (add (dec 3) (inc 6)))
    (add (add 2 7))
    (add (add (dec 2) (inc 7)))
    (add (add 1 8))
    (add (add (dec 1) (inc 8)))
    (add (add 0 9))
    (add 0 9)
    9
          


  ; The 1 first solution is a recursive process and 2 solution is a iterative process.